### ISSUE TITLE
Customize header level

### ISSUE THREAD

**Issue by tdszyman** [inaki-ibarra/vscode-daily-notes#7]
Thanks for this plugin! So simple and easy, it's exactly what I need.

I would prefer the date entries to be H1 headers `#` not H2 `##`, but it looks like this is hard-coded. It would be nice if this was customisable, either as a separate parameter or inside the `Date Format` setting. 

Possibly this could just changing this line:

```return "## " + moment(today).format(configDateFormat) + "\r\n\r\n\r\n";```

To this:

```return moment(today).format(configDateFormat);```

So the user can completely customise the format including the header and whitespace.

**Comment by inaki-ibarra** [comment]
I think this a good idea, although I'm not sure if combining Markdown tag in Date format is the way to go since it could affect those users with existing Date format override. Another option is to add a DateTime Tag in the config. Between the 2, your suggestion offers more flexibility. Either way, I'll add this feature to the next release. Feel free to submit a PR if you want.
